[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_BASE_URL = "https://7dm1erset7.execute-api.ap-northeast-1.amazonaws.com/prod"
  VITE_USER_POOL_ID = "ap-northeast-1_m1LkBYqEc"
  VITE_USER_POOL_CLIENT_ID = "7f5hft1ip7gp9kqdh58bidsc4r"
  VITE_REGION = "ap-northeast-1"
  VITE_USE_MOCK_DATA = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 