name: Deploy to AWS Amplify

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build application
        run: npm run build
        env:
          VITE_API_BASE_URL: https://7dm1erset7.execute-api.ap-northeast-1.amazonaws.com/prod
          VITE_USER_POOL_ID: ap-northeast-1_m1LkBYqEc
          VITE_USER_POOL_CLIENT_ID: 7f5hft1ip7gp9kqdh58bidsc4r
          VITE_REGION: ap-northeast-1
          VITE_USE_MOCK_DATA: false
          
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-1
          SOURCE_DIR: dist 